baseURL = 'https://kaveeshanirmal.github.io/devhub'
languageCode = 'en-us'
title = 'Kaveesha Nirmal'
theme = 'hugo-theme-stack'

[pagination]
    pagerSize = 10

hasCJKLanguage = false

[params]
    mainSections = ['post', 'projects']
    featuredImageField = 'image'
    rssFullContent = true
    favicon = '/favicon.ico'

    [params.footer]
        since = 2024
        customText = '© 2025 Kaveesha Nirmal. All rights reserved.'

    [params.dateFormat]
        published = 'Jan 02, 2006'
        lastUpdated = 'Jan 02, 2006 15:04 MST'

    [params.sidebar]
        subtitle = 'Computer Science Undergraduate | DevOps Enthusiast'
        
        [params.sidebar.avatar]
            enabled = true
            local = true
            src = 'me.png'

    [params.article]
        math = false
        toc = true
        readingTime = true
        
        [params.article.license]
            enabled = false

    [params.comments]
        enabled = false

    [params.widgets]
        homepage = [
            { type = 'search' },
            { type = 'archives', params = { limit = 5 } },
            { type = 'categories', params = { limit = 10 } },
            { type = 'tag-cloud', params = { limit = 10 } }
        ]
        page = [
            { type = 'toc' }
        ]

    [params.opengraph]
        [params.opengraph.twitter]
            site = '@yourtwitterhandle'
            card = 'summary_large_image'

    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ''

# Menu configuration
[[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = -100
    [menu.main.params]
        icon = 'home'
        newTab = false

[[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/page/about/'
    weight = -90
    [menu.main.params]
        icon = 'user'
        newTab = false

[[menu.main]]
    identifier = 'projects'
    name = 'Projects'
    url = '/projects/'
    weight = -80
    [menu.main.params]
        icon = 'code'
        newTab = false

[[menu.main]]
    identifier = 'resume'
    name = 'Resume'
    url = '/resume/'
    weight = -70
    [menu.main.params]
        icon = 'file'
        newTab = false

# Social menu
[[menu.social]]
    identifier = 'github'
    name = 'GitHub'
    url = 'https://github.com/kaveeshanirmal'
    [menu.social.params]
        icon = 'brand-github'

[[menu.social]]
    identifier = 'linkedin'
    name = 'LinkedIn'
    url = 'https://linkedin.com/in/kaveeshanirmal'
    [menu.social.params]
        icon = 'brand-linkedin'

[[menu.social]]
    identifier = 'email'
    name = 'Email'
    url = 'mailto:kaveeshanirmal02@gmail.com'
    [menu.social.params]
        icon = 'mail'
